apiVersion: v1
kind: Service
metadata:
  name: app-payment-postgres
spec:
  selector:
    app: app-payment-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
